### ISSUE TITLE
Release 0.6.0 on Maven Central

### ISSUE THREAD

**Issue by keuhdall** [profunktor/http4s-jwt-auth#266]
Hello,

Sorry to bother you with such an issue, but I was looking forward using your library on a project I have, however I still haven't performed the migration from CE2 to CE3 on it, and I don't feel like I'm quite ready to do it yet.
Since your 0.6.0 version still uses CE2, I was wondering if you could release it on Maven Central, as I might not be the only one in that situation.

Thank you

**Comment by gvolpe** [comment]
Version `0.0.6` is already on [Maven Central](https://search.maven.org/artifact/dev.profunktor/http4s-jwt-auth_2.13/0.0.6/jar).

Anyway, I just published [v0.0.7](https://github.com/profunktor/http4s-jwt-auth/releases/tag/v0.0.7) and it's already up on [Maven Central](https://search.maven.org/artifact/dev.profunktor/http4s-jwt-auth_2.13/0.0.7/jar).
