### ISSUE TITLE
Release to maven central

### ISSUE THREAD

**Issue by froth** [profunktor/http4s-jwt-auth#365]
Hi,

would it be possible to get a release of the current master? (Maybe with updated dependencies)

Greetings and thanks!

**Comment by gvolpe** [comment]
Sorry it's taken so long! If you use this library in production, please consider becoming a maintainer. This one is quite little so it doesn't need much time, but a little love is always appreciated :)

https://github.com/profunktor/http4s-jwt-auth/releases/tag/v1.1.0

**Comment by gvolpe** [comment]
Damn... GPG issues on the release process, it's been a while. I'll try to have a look sometime this week or the weekend, quite busy at work right now.

**Comment by froth** [comment]
Thanks for having a look.

If you are willing to give me access I can totally help maintaining this library.

**Comment by froth** [comment]
I think the gpg issue has to be resolved by you, otherwise (at least from what I remember of with the publish plugin) I would have to generate a new key.

**Comment by gvolpe** [comment]
Yes, I created a new GPG key, but that was not enough. We are hitting this issue https://github.com/olafurpg/setup-gpg/issues/8

As soon as I have some time, I'll remove this action and use Nix instead to get the `gpg` binary set up.

FYI: You should have received an invitation to join this repo as a maintainer :)

**Comment by froth** [comment]
> FYI: You should have received an invitation to join this repo as a maintainer :)

Thanks for the trust! I will do my best to help :)

**Comment by froth** [comment]
> Yes, I created a new GPG key, but that was not enough. We are hitting this issue [olafurpg/setup-gpg#8](https://github.com/olafurpg/setup-gpg/issues/8)

If I compare the log of the push on this repo with my (very similarly setup) repo over here: https://github.com/medeia/medeia/actions/runs/3637985691/jobs/6139676119, it looks like the keychain here is missing the public-key 

```
gpg: Total number processed: 1
gpg:       secret keys read: 1
gpg:   secret keys imported: 1
```

resulting in 
```
[info] gpg: key FFFFFFFF: secret key without public key - skipped
```

vs.

```
gpg: Total number processed: 1
gpg:               imported: 1
gpg:       secret keys read: 1
gpg:   secret keys imported: 1
```

I am not sure if this is really the problem but maybe it is worth a try to check whether the public-key is in the keychain.

But +1 for more Nix in any case ;)

**Comment by gvolpe** [comment]
https://github.com/profunktor/http4s-jwt-auth/releases/tag/v1.2.0

Arrrghh so many things went wrong with Sonatype 🤕  https://github.com/profunktor/http4s-jwt-auth/actions/runs/4008404561/jobs/6882509634

Can't even log in, getting a 504: https://oss.sonatype.org/

**Comment by gvolpe** [comment]
Well looks like it worked after many retries! 🚀

**Comment by froth** [comment]
Great, thanks!
