### ISSUE TITLE
Release a version with updated dependencies

### ISSUE THREAD

**Issue by froth** [profunktor/http4s-jwt-auth#403]
Hi @gvolpe,

I think it would be a good idea to release a new patch release with the updated dependencies.

I am not sure whether this is something you want to do yourself or if I should do that. If I should take care of it: Is pushing a tag and creating release notes in github enough or is there something else I need to know?

**Comment by gvolpe** [comment]
@froth definitely a good idea 👍🏽 

> Is pushing a tag and creating release notes in github enough

Yes, that should be everything needed. Give it a try and if something goes wrong, I can have look... :)

**Comment by froth** [comment]
Worked fine :) thanks!
