### ISSUE TITLE
http4s 1.0.0-M40 compatibility

### ISSUE THREAD

**Issue by vicaba** [profunktor/http4s-jwt-auth#404]
Hello,

I am trying to set up **http4s 1.0.0-M40** and **http4s-jwt-auth 1.2.1** together, however, on trying to resolve dependencies via `sbt`, I get this binary compatibility error:

```
[error] (update) found version conflict(s) in library dependencies; some are suspected to be binary incompatible:
[error]
[error] 	* org.http4s:http4s-server_3:1.0.0-M40 (early-semver) is selected over 0.23.23
[error] 	    +- org.http4s:http4s-ember-server_3:1.0.0-M40         (depends on 1.0.0-M40)
[error] 	    +- dev.profunktor:http4s-jwt-auth_3:1.2.1             (depends on 0.23.23)
[error]
[error] 	* org.http4s:http4s-dsl_3:1.0.0-M40 (early-semver) is selected over 0.23.23
[error] 	    +- http4s-auth:http4s-auth_3:0.1.0-SNAPSHOT           (depends on 1.0.0-M40)
[error] 	    +- dev.profunktor:http4s-jwt-auth_3:1.2.1             (depends on 0.23.23)
[error]
[error]
[error] this can be overridden using libraryDependencySchemes or evictionErrorLevel
[error] (ssExtractDependencies) found version conflict(s) in library dependencies; some are suspected to be binary incompatible:
[error]
[error] 	* org.http4s:http4s-server_3:1.0.0-M40 (early-semver) is selected over 0.23.23
[error] 	    +- org.http4s:http4s-ember-server_3:1.0.0-M40         (depends on 1.0.0-M40)
[error] 	    +- dev.profunktor:http4s-jwt-auth_3:1.2.1             (depends on 0.23.23)
[error]
[error] 	* org.http4s:http4s-dsl_3:1.0.0-M40 (early-semver) is selected over 0.23.23
[error] 	    +- http4s-auth:http4s-auth_3:0.1.0-SNAPSHOT           (depends on 1.0.0-M40)
[error] 	    +- dev.profunktor:http4s-jwt-auth_3:1.2.1             (depends on 0.23.23)
[error]
[error]
[error] this can be overridden using libraryDependencySchemes or evictionErrorLevel
```

I am not proficient in that matter and do not understand why the error occurred, but adding `VersionScheme.Always` as suggested [here](https://stackoverflow.com/questions/75229578/how-to-use-sbts-librarydependencyscheme-key) solved the issue (at least when `sbt` resolves dependencies).

**Comment by froth** [comment]
Hi, thanks for reporting.

The underlying issue is that this library is built against the stable 0.23 branch of http4s and you are using the 1.0.0 development version of http4s. The 1.0.0 version is not fully compatible with 0.23. We will support 1.0.0 once it is officially released (there are still breaking changes added to the 1.0.0 series). If it works with `VersionScheme.Always` that's nice but there is no guarantee for it for coming 1.0.0 milestones :)

I hope that helps!

**Comment by froth** [comment]
I think I will add the information to the readme, to make this more transparent.

**Comment by vicaba** [comment]
Hi,

Thanks for your quick response. I just tried it. Dependency resolution works, but not when importing it during coding. I think it is a good idea to add this to the readme.

I leave up to you closing this issue. As far as I am concerned, it can be closed!
