### ISSUE TITLE
Publishing fails because sonatype credentials have to be changed 

### ISSUE THREAD

**Issue by froth** [profunktor/http4s-jwt-auth#453]
The last publish jobs fail with "too many redirects" exceptions. This is sonatypes strange way of saying "we have changed auth to tokens instead of user user and password".

Link to the documentation of how to create tokens: 
https://central.sonatype.org/publish/generate-token/

@gvolpe I believe this is something only you can do

**Comment by gvolpe** [comment]
Thanks, same issue on https://github.com/profunktor/redis4cats/issues/891

Will look into it the new docs, this is always painful 😭

**Comment by gvolpe** [comment]
This is fixed now 👍🏽
