### ISSUE TITLE
Release 2.0

### ISSUE THREAD

**Issue by froth** [profunktor/http4s-jwt-auth#457]
We will need to release a new major version, to ship the changes in https://github.com/profunktor/http4s-jwt-auth/pull/452.

To do so I created a new branch series/2.x. @gvolpe could you change the github settings so that this is the new default branch?
I think that I did the needed changes so that the new branch can release artefacts in https://github.com/profunktor/http4s-jwt-auth/commit/bbd7b8ee5a29a26ee7b5c61c6ba6f9a460b18352 if something is missing a hint would be appreciated :)

I will release a (hopefully) last 1.x version once sonatype is alive again. (done https://github.com/profunktor/http4s-jwt-auth/releases/tag/v1.2.3)

Additionally, we should think about other breaking changes that could be made, now that we have a major release coming up anyways.

I will leave this issue open for some time, so that there is a chance that other breaking ideas can come in.

**Comment by gvolpe** [comment]
Done 👍🏽

**Comment by froth** [comment]
Has been open long enough. Will do the release today.
